name: "Detect Secrets Action"
author: "Arne Morten Johansen"
inputs:
  new_files:
    description: "Files to scan"
  skip_issue:
    description: "Skips Issue creation in repo if set to true"
    default: "false"
  baseline_file:
    description: "path to baseline file"
    default: ".secrets.baseline"
  exceptions:
    description: "list of exceptions using regular exceptions."
    default: "[]"
  docs_url:
    description: "Will link to this URL from the issues created"
outputs:
  secrethook:
    description: "Secrets detected"
runs:
  using: "docker"
  image: "Dockerfile"
