name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Self test
        continue-on-error: true
        id: selftest
        uses: arnemorten/py-detect-secrets@master
        with: 
          new_files: '["tests/secrets.txt"]'
          skip_issue: 'true'
          baseline_file: "tests/.secrets.baseline"
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.secrethook }}" == "secret_detected"
