name: Lint
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3

      - name: Lint
        run: |
          pip install flake8
          flake8 --max-line-length=120 main.py
